<div class="grid gap-5">
    <div class="flex flex-wrap items-end justify-between gap-3">
        <div><a href="{{ route('sysadmin.enquiry.index') }}" class="inline-flex items-center gap-1 text-xs font-semibold text-primary">{!! \Modules\SysAdmin\Support\Icon::get('arrow-left', 'h-3.5 w-3.5') !!} Enquiry CRM</a><h1 class="mt-1.5 text-[22px] font-bold tracking-tight text-ink">Appointments</h1><p class="mt-1 text-[13px] text-ink-muted">Calls, meetings and site visits scheduled from enquiries.</p></div>
        @can('customer.enquiries.update')<x-sysadmin::btn variant="primary" wire:click="openForm">{!! \Modules\SysAdmin\Support\Icon::get('plus', 'h-4 w-4') !!} Schedule appointment</x-sysadmin::btn>@endcan
    </div>

    <x-sysadmin::table-toolbar search-placeholder="Search appointment, customer, phone or email…">
        <select wire:model.live="period" class="min-h-11 rounded-xl border border-hairline-strong bg-white px-3 text-[12px] font-semibold text-ink"><option value="upcoming">Upcoming</option><option value="today">Today</option><option value="past">Past</option><option value="all">All dates</option></select>
        <select wire:model.live="status" class="min-h-11 rounded-xl border border-hairline-strong bg-white px-3 text-[12px] font-semibold text-ink"><option value="">All statuses</option>@foreach(\Modules\SysAdmin\Models\EnquiryAppointment::$statuses as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select>
        <select wire:model.live="assignedTo" class="min-h-11 rounded-xl border border-hairline-strong bg-white px-3 text-[12px] font-semibold text-ink"><option value="">All owners</option><option value="unassigned">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select>
    </x-sysadmin::table-toolbar>

    <div wire:loading.class="opacity-60" class="overflow-x-auto rounded-xl border border-hairline bg-white shadow-sm transition">
        <table class="w-full min-w-[900px] border-collapse"><thead><tr><x-sysadmin::th>Date and time</x-sysadmin::th><x-sysadmin::th>Appointment</x-sysadmin::th><x-sysadmin::th>Customer</x-sysadmin::th><x-sysadmin::th>Type / location</x-sysadmin::th><x-sysadmin::th>Owner</x-sysadmin::th><x-sysadmin::th>Status</x-sysadmin::th><x-sysadmin::th align="right">Enquiry</x-sysadmin::th></tr></thead><tbody>
            @forelse($appointments as $appointment)
                <tr wire:key="appointment-{{ $appointment->id }}" class="hover:bg-[#fafbfc]">
                    <x-sysadmin::td><div class="flex items-center gap-3"><div class="w-11 rounded-lg bg-violet-50 py-1.5 text-center text-violet-700"><strong class="block text-sm">{{ $appointment->starts_at->format('d') }}</strong><span class="text-[9px] font-bold uppercase">{{ $appointment->starts_at->format('M') }}</span></div><span><strong class="block whitespace-nowrap text-[12.5px] text-ink">{{ $appointment->starts_at->format('h:i A') }}</strong><small class="text-[10.5px] text-ink-muted">{{ $appointment->starts_at->format('Y') }}</small></span></div></x-sysadmin::td>
                    <x-sysadmin::td><strong class="block max-w-56 truncate text-[12.5px] text-ink">{{ $appointment->title }}</strong>@if($appointment->ends_at)<span class="text-[10.5px] text-ink-muted">Ends {{ $appointment->ends_at->format('h:i A') }}</span>@endif</x-sysadmin::td>
                    <x-sysadmin::td><strong class="block text-[12px] text-ink-soft">{{ $appointment->customer_name }}</strong><span class="block text-[10.5px] text-ink-muted">{{ $appointment->mobile ?: $appointment->email ?: 'No contact' }}</span></x-sysadmin::td>
                    <x-sysadmin::td><span class="block text-[11.5px] font-semibold text-ink-soft">{{ \Modules\SysAdmin\Models\EnquiryAppointment::$meetingTypes[$appointment->meeting_type] ?? str($appointment->meeting_type)->headline() }}</span><span class="block max-w-44 truncate text-[10.5px] text-ink-muted">{{ $appointment->location ?: 'Not set' }}</span></x-sysadmin::td>
                    <x-sysadmin::td><span class="text-[11.5px] text-ink-soft">{{ $appointment->assignedUser?->name ?? 'Unassigned' }}</span></x-sysadmin::td>
                    <x-sysadmin::td>@can('customer.enquiries.update')<select wire:change="updateStatus({{ $appointment->id }}, $event.target.value)" class="min-h-8 rounded-lg border border-hairline-strong bg-white px-2 text-[11px] font-semibold text-ink">@foreach(\Modules\SysAdmin\Models\EnquiryAppointment::$statuses as $key => $label)<option value="{{ $key }}" @selected($appointment->status === $key)>{{ $label }}</option>@endforeach</select>@else<span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-ink-soft">{{ \Modules\SysAdmin\Models\EnquiryAppointment::$statuses[$appointment->status] ?? $appointment->status }}</span>@endcan</x-sysadmin::td>
                    <x-sysadmin::td align="right">@if($appointment->enquiry)<x-sysadmin::icon-button icon="eye" label="Open enquiry" :href="route('sysadmin.enquiry.view', $appointment->enquiry_id)" />@else<span class="text-[11px] text-ink-muted">Unlinked</span>@endif</x-sysadmin::td>
                </tr>
            @empty
                <tr><td colspan="7" class="px-6 py-14 text-center"><strong class="block text-[13px] text-ink">No appointments found</strong><span class="mt-1 block text-xs text-ink-muted">Change the filters or schedule an appointment.</span></td></tr>
            @endforelse
        </tbody></table>
    </div>
    @if($appointments->hasPages())<div>{{ $appointments->links() }}</div>@endif

    @if($formOpen)
        <div class="fixed inset-0 z-50" role="dialog" aria-modal="true"><button type="button" wire:click="closeForm" class="absolute inset-0 bg-slate-950/40" aria-label="Close"></button><aside class="absolute inset-y-0 right-0 w-full max-w-lg overflow-y-auto bg-white shadow-2xl"><div class="flex items-start justify-between border-b border-hairline px-6 py-5"><div><h2 class="text-lg font-bold text-ink">Schedule appointment</h2><p class="mt-1 text-xs text-ink-muted">Link the appointment to an active enquiry.</p></div><button type="button" wire:click="closeForm" class="grid size-9 place-items-center rounded-lg text-xl text-ink-muted hover:bg-slate-100">×</button></div><form wire:submit="save" class="grid gap-4 p-6"><x-sysadmin::select label="Enquiry" name="enquiryId" wire:model.live="enquiryId" required><option value="">Select an enquiry</option>@foreach($enquiries as $enquiry)<option value="{{ $enquiry->id }}">#{{ $enquiry->id }} · {{ $enquiry->name }}{{ $enquiry->subject ? ' — '.$enquiry->subject : '' }}</option>@endforeach</x-sysadmin::select><x-sysadmin::input label="Appointment title" name="title" wire:model="title" required /><div class="grid gap-4 sm:grid-cols-2"><x-sysadmin::input label="Starts" name="startsAt" type="datetime-local" wire:model="startsAt" required /><x-sysadmin::input label="Ends" name="endsAt" type="datetime-local" wire:model="endsAt" /></div><x-sysadmin::select label="Meeting type" name="meetingType" wire:model="meetingType" required>@foreach(\Modules\SysAdmin\Models\EnquiryAppointment::$meetingTypes as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</x-sysadmin::select><x-sysadmin::input label="Location or meeting link" name="location" wire:model="location" /><x-sysadmin::select label="Assigned to" name="formAssignedTo" wire:model="formAssignedTo"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</x-sysadmin::select><div><label class="mb-1.5 block text-[12.5px] font-bold text-ink">Notes</label><textarea wire:model="notes" rows="4" class="w-full rounded-xl border border-hairline-strong px-3 py-2.5 text-[13px]"></textarea>@error('notes')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="mt-2 flex justify-end gap-2 border-t border-hairline pt-5"><x-sysadmin::btn wire:click="closeForm">Cancel</x-sysadmin::btn><x-sysadmin::btn type="submit" variant="primary" wire:loading.attr="disabled">Schedule appointment</x-sysadmin::btn></div></form></aside></div>
    @endif
</div>
