<div class="grid gap-5">
    <div class="flex flex-wrap items-end justify-between gap-3">
        <div><a href="{{ route('sysadmin.enquiry.index') }}" class="inline-flex items-center gap-1 text-xs font-semibold text-primary">{!! \Modules\SysAdmin\Support\Icon::get('arrow-left', 'h-3.5 w-3.5') !!} Enquiry CRM</a><div class="mt-2 flex flex-wrap items-center gap-2"><h1 class="text-[22px] font-bold tracking-tight text-ink">{{ $enquiry->name }}</h1><span class="inline-flex rounded-full px-2.5 py-1 text-[10.5px] font-bold {{ \Modules\SysAdmin\Models\Enquiry::statusClasses((int)$enquiry->status) }}">{{ \Modules\SysAdmin\Models\Enquiry::$statuses[(int)$enquiry->status] ?? $enquiry->status }}</span></div><p class="mt-1 text-[13px] text-ink-muted">{{ $enquiry->subject ?: 'General enquiry' }} · Received {{ $enquiry->created_at?->diffForHumans() }}</p></div>
        <div class="flex flex-wrap gap-2">@can('customer.enquiries.update')<x-sysadmin::btn wire:click="openFollowUp">{!! \Modules\SysAdmin\Support\Icon::get('plus', 'h-4 w-4') !!} Follow-up</x-sysadmin::btn><x-sysadmin::btn wire:click="openAppointment">Schedule appointment</x-sysadmin::btn><x-sysadmin::btn variant="primary" :href="route('sysadmin.enquiry.edit', $enquiry->id)">Edit enquiry</x-sysadmin::btn>@endcan</div>
    </div>

    <div class="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
        <div class="grid min-w-0 gap-4">
            <x-sysadmin::card>
                <div class="flex flex-wrap items-start justify-between gap-3 border-b border-hairline px-4 py-3"><div><h2 class="text-sm font-bold text-ink">Customer and request</h2><p class="mt-0.5 text-[11px] text-ink-muted">Primary enquiry information</p></div><div class="flex gap-2">@if($enquiry->mobile)<a href="tel:{{ $enquiry->mobile }}" class="rounded-lg bg-primary-50 px-3 py-2 text-xs font-bold text-primary">Call</a>@endif @if($enquiry->email)<a href="mailto:{{ $enquiry->email }}" class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-ink-soft">Email</a>@endif</div></div>
                <div class="grid gap-5 p-4 md:grid-cols-2">
                    <div class="grid gap-3 text-[12.5px]"><div><span class="block text-[10.5px] font-bold uppercase tracking-wide text-ink-muted">Contact</span><strong class="mt-1 block text-ink">{{ $enquiry->mobile }}</strong><span class="block text-ink-soft">{{ $enquiry->email ?: 'No email' }}</span></div><div><span class="block text-[10.5px] font-bold uppercase tracking-wide text-ink-muted">Location</span><span class="mt-1 block text-ink-soft">{{ collect([$enquiry->city, $enquiry->state])->filter()->join(', ') ?: 'Not provided' }}</span></div><div><span class="block text-[10.5px] font-bold uppercase tracking-wide text-ink-muted">Source</span><span class="mt-1 block text-ink-soft">{{ str($enquiry->enquiry_type ?: 'Not recorded')->headline() }}</span></div></div>
                    <div class="grid gap-3 text-[12.5px]"><div><span class="block text-[10.5px] font-bold uppercase tracking-wide text-ink-muted">Product</span><strong class="mt-1 block text-ink">{{ $enquiry->product?->title ?: 'General request' }}</strong><span class="block text-ink-soft">{{ $enquiry->category?->name ?: 'No category' }}</span></div><div class="grid grid-cols-3 gap-2"><div><span class="block text-[10px] uppercase text-ink-muted">Qty</span><strong class="text-ink">{{ $enquiry->qty > 0 ? $enquiry->qty : '—' }}</strong></div><div><span class="block text-[10px] uppercase text-ink-muted">Price</span><strong class="text-ink">{{ $enquiry->price > 0 ? number_format((float)$enquiry->price, 2) : '—' }}</strong></div><div><span class="block text-[10px] uppercase text-ink-muted">Requested</span><strong class="text-ink">{{ $enquiry->req_price > 0 ? number_format((float)$enquiry->req_price, 2) : '—' }}</strong></div></div></div>
                    <div class="md:col-span-2"><span class="block text-[10.5px] font-bold uppercase tracking-wide text-ink-muted">Customer message</span><p class="mt-2 whitespace-pre-line rounded-xl bg-[#fafbfc] p-4 text-[13px] leading-relaxed text-ink-soft">{{ $enquiry->message }}</p></div>
                    @if($enquiry->internal_notes)<div class="md:col-span-2"><span class="block text-[10.5px] font-bold uppercase tracking-wide text-ink-muted">Internal notes</span><p class="mt-2 whitespace-pre-line rounded-xl border border-amber-100 bg-amber-50/60 p-4 text-[13px] leading-relaxed text-amber-900">{{ $enquiry->internal_notes }}</p></div>@endif
                </div>
            </x-sysadmin::card>

            <x-sysadmin::card>
                <div class="flex items-center justify-between border-b border-hairline px-4 py-3"><div><h2 class="text-sm font-bold text-ink">Follow-up tasks</h2><p class="mt-0.5 text-[11px] text-ink-muted">Calls, messages, meetings and next actions</p></div>@can('customer.enquiries.update')<button type="button" wire:click="openFollowUp" class="text-xs font-bold text-primary">Add task</button>@endcan</div>
                <div class="divide-y divide-hairline">
                    @forelse($enquiry->followUps as $followUp)
                        <div class="flex flex-wrap items-start gap-3 px-4 py-3.5">
                            <span class="grid size-9 shrink-0 place-items-center rounded-lg {{ $followUp->status === 'completed' ? 'bg-emerald-50 text-emerald-700' : ($followUp->status === 'cancelled' ? 'bg-slate-100 text-slate-500' : ($followUp->scheduled_at->isPast() ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700')) }}">{!! \Modules\SysAdmin\Support\Icon::get($followUp->status === 'completed' ? 'check' : 'message', 'h-4 w-4') !!}</span>
                            <div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><strong class="text-[13px] text-ink">{{ $followUp->subject }}</strong><span class="rounded-full bg-slate-100 px-2 py-0.5 text-[9.5px] font-bold uppercase text-ink-muted">{{ str($followUp->type)->headline() }}</span></div><p class="mt-1 text-[11.5px] {{ $followUp->status === 'pending' && $followUp->scheduled_at->isPast() ? 'font-semibold text-red-600' : 'text-ink-muted' }}">{{ $followUp->scheduled_at->format('d M Y, h:i A') }} · {{ $followUp->assignedUser?->name ?? 'Unassigned' }}</p>@if($followUp->notes)<p class="mt-1.5 text-[12px] text-ink-soft">{{ $followUp->notes }}</p>@endif</div>
                            @if($followUp->status === 'pending')
                                @can('customer.enquiries.update')
                                    <div class="flex gap-1"><button type="button" wire:click="completeFollowUp({{ $followUp->id }})" wire:confirm="Mark this follow-up completed?" class="rounded-lg bg-emerald-50 px-2.5 py-1.5 text-[10.5px] font-bold text-emerald-700">Complete</button><button type="button" wire:click="cancelFollowUp({{ $followUp->id }})" wire:confirm="Cancel this follow-up?" class="rounded-lg px-2.5 py-1.5 text-[10.5px] font-bold text-red-600 hover:bg-red-50">Cancel</button></div>
                                @endcan
                            @endif
                        </div>
                    @empty
                        <div class="px-5 py-10 text-center"><strong class="block text-[13px] text-ink">No follow-up tasks</strong><span class="mt-1 block text-xs text-ink-muted">Schedule the next customer action so it is not missed.</span></div>
                    @endforelse
                </div>
            </x-sysadmin::card>

            <x-sysadmin::card>
                <div class="flex items-center justify-between border-b border-hairline px-4 py-3"><div><h2 class="text-sm font-bold text-ink">Appointments</h2><p class="mt-0.5 text-[11px] text-ink-muted">Meetings and site visits linked to this enquiry</p></div><a href="{{ route('sysadmin.enquiry.appointments') }}" class="text-xs font-bold text-primary">View calendar list</a></div>
                <div class="divide-y divide-hairline">@forelse($enquiry->appointments as $appointment)<div class="flex items-start gap-3 px-4 py-3.5"><div class="w-12 shrink-0 rounded-lg bg-violet-50 py-2 text-center text-violet-700"><strong class="block text-sm">{{ $appointment->starts_at->format('d') }}</strong><span class="text-[9px] font-bold uppercase">{{ $appointment->starts_at->format('M') }}</span></div><div class="min-w-0 flex-1"><strong class="block text-[13px] text-ink">{{ $appointment->title }}</strong><span class="mt-1 block text-[11.5px] text-ink-muted">{{ $appointment->starts_at->format('h:i A') }}@if($appointment->ends_at)–{{ $appointment->ends_at->format('h:i A') }}@endif · {{ \Modules\SysAdmin\Models\EnquiryAppointment::$meetingTypes[$appointment->meeting_type] ?? str($appointment->meeting_type)->headline() }}</span><span class="block text-[11px] text-ink-muted">{{ $appointment->location ?: 'Location not set' }} · {{ $appointment->assignedUser?->name ?? 'Unassigned' }}</span></div><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-ink-soft">{{ \Modules\SysAdmin\Models\EnquiryAppointment::$statuses[$appointment->status] ?? str($appointment->status)->headline() }}</span></div>@empty<div class="px-5 py-10 text-center text-xs text-ink-muted">No appointments scheduled.</div>@endforelse</div>
            </x-sysadmin::card>

            <x-sysadmin::card>
                <div class="border-b border-hairline px-4 py-3"><h2 class="text-sm font-bold text-ink">Activity timeline</h2></div>
                @can('customer.enquiries.update')<form wire:submit="addNote" class="flex gap-2 border-b border-hairline p-4"><input wire:model="activityNote" type="text" placeholder="Add an internal timeline note…" class="min-h-10 flex-1 rounded-lg border border-hairline-strong px-3 text-[13px] focus:border-primary focus:outline-none"><x-sysadmin::btn type="submit">Add note</x-sysadmin::btn></form>@error('activityNote')<p class="px-4 pb-3 text-xs text-red-600">{{ $message }}</p>@enderror@endcan
                <div class="p-4"><ol class="relative ml-2 border-l border-hairline pl-5">@forelse($enquiry->activities->take(30) as $activity)<li class="relative pb-5 last:pb-0"><span class="absolute -left-[25px] top-1 size-2 rounded-full bg-primary ring-4 ring-white"></span><p class="text-[12.5px] text-ink-soft">{{ $activity->description }}</p><span class="mt-1 block text-[10.5px] text-ink-muted">{{ $activity->creator?->name ?? 'System' }} · {{ $activity->created_at?->format('d M Y, h:i A') }}</span></li>@empty<li class="text-xs text-ink-muted">No activity recorded yet.</li>@endforelse</ol></div>
            </x-sysadmin::card>
        </div>

        <aside class="grid content-start gap-4">
            <x-sysadmin::card>
                <div class="border-b border-hairline px-4 py-3"><h2 class="text-sm font-bold text-ink">Pipeline status</h2></div>
                <div class="grid gap-3 p-4"><x-sysadmin::select label="Status" name="status" wire:model="status" size="sm">@foreach(\Modules\SysAdmin\Models\Enquiry::$statuses as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</x-sysadmin::select>@can('customer.enquiries.update')<x-sysadmin::btn type="button" variant="primary" wire:click="updateStatus" class="w-full">Update status</x-sysadmin::btn>@endcan</div>
            </x-sysadmin::card>
            <x-sysadmin::card>
                <div class="border-b border-hairline px-4 py-3"><h2 class="text-sm font-bold text-ink">Ownership</h2></div>
                <div class="grid gap-3 p-4"><x-sysadmin::select label="Priority" name="priority" wire:model="priority" size="sm">@foreach(\Modules\SysAdmin\Models\Enquiry::$priorities as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</x-sysadmin::select><x-sysadmin::select label="Assigned to" name="assignedTo" wire:model="assignedTo" size="sm"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</x-sysadmin::select>@can('customer.enquiries.update')<x-sysadmin::btn type="button" wire:click="saveAssignment" class="w-full">Save ownership</x-sysadmin::btn>@endcan</div>
            </x-sysadmin::card>
            <x-sysadmin::card padded><h3 class="text-xs font-bold uppercase tracking-wide text-ink-muted">Next follow-up</h3>@if($enquiry->next_follow_up_at)<strong class="mt-2 block text-sm {{ $enquiry->next_follow_up_at->isPast() ? 'text-red-600' : 'text-ink' }}">{{ $enquiry->next_follow_up_at->format('d M Y, h:i A') }}</strong><span class="mt-1 block text-[11px] text-ink-muted">{{ $enquiry->next_follow_up_at->diffForHumans() }}</span>@else<p class="mt-2 text-xs text-ink-muted">No pending action scheduled.</p>@endif@if($enquiry->last_contacted_at)<div class="mt-4 border-t border-hairline pt-3"><span class="text-[10px] font-bold uppercase text-ink-muted">Last contacted</span><span class="mt-1 block text-xs text-ink-soft">{{ $enquiry->last_contacted_at->format('d M Y, h:i A') }}</span></div>@endif</x-sysadmin::card>
        </aside>
    </div>

    @if($followUpOpen)
        <div class="fixed inset-0 z-50" role="dialog" aria-modal="true"><button type="button" wire:click="closePanel" class="absolute inset-0 bg-slate-950/40" aria-label="Close"></button><aside class="absolute inset-y-0 right-0 w-full max-w-lg overflow-y-auto bg-white shadow-2xl"><div class="flex items-start justify-between border-b border-hairline px-6 py-5"><div><h2 class="text-lg font-bold text-ink">Schedule follow-up</h2><p class="mt-1 text-xs text-ink-muted">Create the next action for {{ $enquiry->name }}.</p></div><button type="button" wire:click="closePanel" class="grid size-9 place-items-center rounded-lg text-xl text-ink-muted hover:bg-slate-100">×</button></div><form wire:submit="addFollowUp" class="grid gap-4 p-6"><x-sysadmin::select label="Action type" name="followUpType" wire:model="followUpType" required><option value="call">Phone call</option><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="meeting">Meeting</option><option value="task">General task</option></x-sysadmin::select><x-sysadmin::input label="Task subject" name="followUpSubject" wire:model="followUpSubject" required /><x-sysadmin::input label="Due date and time" name="followUpScheduledAt" type="datetime-local" wire:model="followUpScheduledAt" required /><x-sysadmin::select label="Assigned to" name="followUpAssignedTo" wire:model="followUpAssignedTo"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</x-sysadmin::select><div><label class="mb-1.5 block text-[12.5px] font-bold text-ink">Notes</label><textarea wire:model="followUpNotes" rows="4" class="w-full rounded-xl border border-hairline-strong px-3 py-2.5 text-[13px]"></textarea>@error('followUpNotes')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="mt-2 flex justify-end gap-2 border-t border-hairline pt-5"><x-sysadmin::btn wire:click="closePanel">Cancel</x-sysadmin::btn><x-sysadmin::btn type="submit" variant="primary" wire:loading.attr="disabled">Schedule follow-up</x-sysadmin::btn></div></form></aside></div>
    @endif

    @if($appointmentOpen)
        <div class="fixed inset-0 z-50" role="dialog" aria-modal="true"><button type="button" wire:click="closePanel" class="absolute inset-0 bg-slate-950/40" aria-label="Close"></button><aside class="absolute inset-y-0 right-0 w-full max-w-lg overflow-y-auto bg-white shadow-2xl"><div class="flex items-start justify-between border-b border-hairline px-6 py-5"><div><h2 class="text-lg font-bold text-ink">Schedule appointment</h2><p class="mt-1 text-xs text-ink-muted">Book a call, meeting or site visit.</p></div><button type="button" wire:click="closePanel" class="grid size-9 place-items-center rounded-lg text-xl text-ink-muted hover:bg-slate-100">×</button></div><form wire:submit="addAppointment" class="grid gap-4 p-6"><x-sysadmin::input label="Appointment title" name="appointmentTitle" wire:model="appointmentTitle" required /><div class="grid gap-4 sm:grid-cols-2"><x-sysadmin::input label="Starts" name="appointmentStartsAt" type="datetime-local" wire:model="appointmentStartsAt" required /><x-sysadmin::input label="Ends" name="appointmentEndsAt" type="datetime-local" wire:model="appointmentEndsAt" /></div><x-sysadmin::select label="Meeting type" name="appointmentType" wire:model="appointmentType" required>@foreach(\Modules\SysAdmin\Models\EnquiryAppointment::$meetingTypes as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</x-sysadmin::select><x-sysadmin::input label="Location or meeting link" name="appointmentLocation" wire:model="appointmentLocation" /><x-sysadmin::select label="Assigned to" name="appointmentAssignedTo" wire:model="appointmentAssignedTo"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</x-sysadmin::select><div><label class="mb-1.5 block text-[12.5px] font-bold text-ink">Notes</label><textarea wire:model="appointmentNotes" rows="4" class="w-full rounded-xl border border-hairline-strong px-3 py-2.5 text-[13px]"></textarea>@error('appointmentNotes')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="mt-2 flex justify-end gap-2 border-t border-hairline pt-5"><x-sysadmin::btn wire:click="closePanel">Cancel</x-sysadmin::btn><x-sysadmin::btn type="submit" variant="primary" wire:loading.attr="disabled">Schedule appointment</x-sysadmin::btn></div></form></aside></div>
    @endif
</div>
