<div class="grid gap-5">
    <div class="flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-[22px] font-bold tracking-tight text-ink">Product attributes</h1><p class="mt-1 text-[13px] text-ink-muted">Reusable fields shared across product families, filters and variants.</p></div><x-sysadmin::btn variant="primary" :href="route('sysadmin.catalog.attribute.create')">{!! \Modules\SysAdmin\Support\Icon::get('plus', 'h-4 w-4') !!} New attribute</x-sysadmin::btn></div>
    @error('delete')<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-red-700">{{ $message }}</div>@enderror
    <x-sysadmin::table-toolbar search-placeholder="Search label or code...">
        <select wire:model.live="family" class="min-h-11 rounded-xl border border-hairline-strong bg-white px-3 text-[12.5px] font-semibold"><option value="all">All families</option>@foreach($families as $familyOption)<option value="{{ $familyOption->id }}">{{ $familyOption->name }}</option>@endforeach</select>
        <select wire:model.live="usage" class="min-h-11 rounded-xl border border-hairline-strong bg-white px-3 text-[12.5px] font-semibold"><option value="all">All uses</option><option value="filterable">Filterable</option><option value="configurable">Configurable</option><option value="comparable">Comparable</option></select>
        <select wire:model.live="status" class="min-h-11 rounded-xl border border-hairline-strong bg-white px-3 text-[12.5px] font-semibold"><option value="all">All statuses</option><option value="1">Published</option><option value="2">Draft</option><option value="0">Disabled</option></select>
    </x-sysadmin::table-toolbar>
    <div wire:loading.class="opacity-60" class="overflow-x-auto rounded-xl border border-hairline bg-white shadow-sm transition">
        <table class="w-full min-w-[900px] border-collapse"><thead><tr><x-sysadmin::th><button wire:click="sort('name')" class="inline-flex items-center gap-1.5 hover:text-primary">Attribute {!! \Modules\SysAdmin\Support\Icon::get('sort', 'h-3.5 w-3.5') !!}</button></x-sysadmin::th><x-sysadmin::th>Type</x-sysadmin::th><x-sysadmin::th>Families / groups</x-sysadmin::th><x-sysadmin::th>Usage</x-sysadmin::th><x-sysadmin::th>Status</x-sysadmin::th><x-sysadmin::th align="right">Actions</x-sysadmin::th></tr></thead>
            <tbody>@forelse($attributeRows as $attribute)<tr wire:key="attribute-{{ $attribute->id }}" class="hover:bg-[#fafbfc]">
                <x-sysadmin::td><div class="font-semibold text-ink">{{ $attribute->name }}</div><code class="mt-0.5 block text-[11.5px] text-primary">{{ $attribute->code }}</code></x-sysadmin::td>
                <x-sysadmin::td><span class="text-[13px] text-ink-soft">{{ $attribute->attribute_type?->type_name ?? 'Unknown' }}</span></x-sysadmin::td>
                <x-sysadmin::td><div class="flex max-w-md flex-wrap gap-1">@forelse($attribute->groups as $group)<span class="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-600">{{ $group->family?->name }} · {{ $group->name }}</span>@empty<span class="text-xs text-ink-muted">Unassigned</span>@endforelse</div></x-sysadmin::td>
                <x-sysadmin::td><div class="flex flex-wrap gap-1">@foreach([['require','Required','bg-red-50 text-red-700'],['filterable','Filter','bg-blue-50 text-blue-700'],['configurable','Variant','bg-primary-50 text-primary-600'],['comparable','Compare','bg-slate-100 text-slate-600']] as [$field,$label,$classes])@if($attribute->{$field})<span class="rounded-full px-2 py-1 text-[10.5px] font-semibold {{ $classes }}">{{ $label }}</span>@endif @endforeach</div></x-sysadmin::td>
                <x-sysadmin::td><span class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11.5px] font-semibold {{ $attribute->status === 1 ? 'bg-emerald-50 text-emerald-700' : ($attribute->status === 2 ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600') }}"><span class="size-1.5 rounded-full bg-current"></span>{{ [0=>'Disabled',1=>'Published',2=>'Draft'][$attribute->status] }}</span></x-sysadmin::td>
                <x-sysadmin::td align="right"><div class="flex justify-end gap-1"><x-sysadmin::icon-button icon="pencil" label="Edit attribute" :href="route('sysadmin.catalog.attribute.edit', $attribute->id)"/><x-sysadmin::icon-button icon="trash" label="Delete attribute" danger wire:click="delete({{ $attribute->id }})" wire:confirm="Delete this attribute?"/></div></x-sysadmin::td>
            </tr>@empty<tr><td colspan="6" class="px-6 py-14 text-center text-[13px] text-ink-muted">No attributes match these filters.</td></tr>@endforelse</tbody>
        </table>
    </div>
    @if($attributeRows->hasPages())<div>{{ $attributeRows->links() }}</div>@endif
</div>
